import green from '@material-ui/core/colors/green';
import blue from '@material-ui/core/colors/blue';
import pink from '@material-ui/core/colors/pink';
import grey from '@material-ui/core/colors/grey';
import red from '@material-ui/core/colors/red';
import orange from '@material-ui/core/colors/orange';
import yellow from '@material-ui/core/colors/yellow';
import brown from '@material-ui/core/colors/brown';
import purple from '@material-ui/core/colors/purple';

import ListIcon from "@material-ui/icons/List";
import AccountBalanceIcon from "@material-ui/icons/AccountBalance";
import GavelIcon from "@material-ui/icons/Gavel";
import PregnantWomanIcon from "@material-ui/icons/PregnantWoman";
import LocalFloristIcon from "@material-ui/icons/LocalFlorist";
import PhonelinkIcon from "@material-ui/icons/Phonelink";
import HearingIcon from "@material-ui/icons/Hearing";
import LocationCityIcon from "@material-ui/icons/LocationCity";
import PeopleIcon from "@material-ui/icons/People";
import TrendingUpIcon from "@material-ui/icons/TrendingUp";
import SchoolIcon from "@material-ui/icons/School";
import AttachMoneyIcon from "@material-ui/icons/AttachMoney";
import MonetizationOnIcon from "@material-ui/icons/MonetizationOn";
import FlashOnIcon from "@material-ui/icons/FlashOn";
import HomeIcon from "@material-ui/icons/Home";
import AccessibleIcon from "@material-ui/icons/Accessible";
import PoolIcon from "@material-ui/icons/Pool";
import LocalLibraryIcon from "@material-ui/icons/LocalLibrary";
import NaturePeopleIcon from "@material-ui/icons/NaturePeople";
import WorkIcon from "@material-ui/icons/Work";
import SecurityIcon from "@material-ui/icons/Security";
import GroupAddIcon from "@material-ui/icons/GroupAdd";
import VpnLockIcon from "@material-ui/icons/VpnLock";
import DeviceHubIcon from "@material-ui/icons/DeviceHub";
import DirectionsBusIcon from "@material-ui/icons/DirectionsBus";
import BuildIcon from "@material-ui/icons/Build";

const comissoes = [
    {
        id: 4,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/4",
        sigla: "MESA",
        nome: "Mesa Diretora da Câmara dos Deputados",
        apelido: "Mesa Diretora",
        codTipoOrgao: 1,
        tipoOrgao: "Comissão Diretora",
        icon: AccountBalanceIcon,
        title: "ABC",
        color: blue[100],
        route: '',
    },
    {
        id: 180,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/180",
        sigla:"PLEN",
        nome: "PLENÁRIO",
        apelido: "PLEN",
        codTipoOrgao: 1,
        tipoOrgao: "Comissão Diretora",
        icon: GavelIcon,
        title: "ABC",
        color: red[100],
        route: '',
    },
    {
        id: 2001,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2001",
        sigla:"CAPADR",
        nome: "Comissão de Agricultura, Pecuária, Abastecimento e Desenvolvimento Rural",
        apelido: "AGRICULTURA, PECUÁRIA, ABASTECIMENTO DESENV. RURAL",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: LocalFloristIcon,
        title: "ABC",
        color: green[100],
        route: '',
    },
    {
        id: 2002,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2002",
        sigla:"CCTCI",
        nome: "Comissão de Ciência e Tecnologia, Comunicação e Informática",
        apelido: "CIÊNCIA E TECNOLOGIA, COMUNICAÇÃO E INFORMÁTICA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: PhonelinkIcon,
        title: "ABC",
        color: grey[200],
        route: '',
    },
    {
        id: 2003,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2003",
        sigla:"CCJC",
        nome: "Comissão de Constituição e Justiça e de Cidadania",
        apelido: "CONSTITUIÇÃO E JUSTIÇA E DE CIDADANIA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: GavelIcon,
        title: "ABC",
        color: blue[100],
        route: '',
    },
    {
        id: 2004,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2004",
        sigla:"CDC",
        nome: "Comissão de Defesa do Consumidor",
        apelido: "DEFESA DO CONSUMIDOR",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: HearingIcon,
        title: "ABC",
        color: red[100],
        route: '',
    },
    {
        id: 2006,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2006",
        sigla:"CDU",
        nome: "Comissão de Desenvolvimento Urbano",
        apelido: "DESENVOLVIMENTO URBANO",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: LocationCityIcon,
        title: "ABC",
        color: grey[100],
        route: '',
    },
    {
        id: 2007,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2007",
        sigla:"CDHM",
        nome: "Comissão de Direitos Humanos e Minorias",
        apelido: "DIREITOS HUMANOS E MINORIAS",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: PeopleIcon,
        title: "ABC",
        color: blue[100],
        route: '',
    },
    {
        id: 2008,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2008",
        sigla:"CDEICS",
        nome: "Comissão de Desenvolvimento Econômico, Indústria, Comércio e Serviços",
        apelido: "DESENVOLV. ECONÔMICO, INDÚSTRIA, COMÉRCIO E SERV.",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: TrendingUpIcon,
        title: "ABC",
        color: red[100],
        route: '',
    },
    {
        id: 2009,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2009",
        sigla:"CE",
        nome: "Comissão de Educação",
        apelido: "EDUCAÇÃO",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: SchoolIcon,
        title: "ABC",
        color: blue[100],
        route: '',
    },
    {
        id: 2010,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2010",
        sigla:"CFT",
        nome: "Comissão de Finanças e Tributação",
        apelido: "FINANÇAS E TRIBUTAÇÃO",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: AttachMoneyIcon,
        title: "ABC",
        color: green[100],
        route: '',
    },
    {
        id: 2011,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2011",
        sigla:"CFFC",
        nome: "Comissão de Fiscalização Financeira e Controle",
        apelido: "FISCALIZAÇÃO FINANCEIRA E CONTROLE",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: MonetizationOnIcon,
        title: "ABC",
        color: green[100],
        route: '',
    },
    {
        id: 2012,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2012",
        sigla:"CME",
        nome: "Comissão de Minas e Energia",
        apelido: "MINAS E ENERGIA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: FlashOnIcon, //BatteryChargingFullIcon,
        title: "ABC",
        color: yellow[100],
        route: '',
    },
    {
        id: 2014,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2014",
        sigla:"CSSF",
        nome: "Comissão de Seguridade Social e Família",
        apelido: "SEGURIDADE SOCIAL E FAMÍLIA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: HomeIcon,
        title: "ABC",
        color: blue[100],
        route: '',
    },
    {
        id: 2015,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2015",
        sigla:"CTASP",
        nome: "Comissão de Trabalho, de Administração e Serviço Público",
        apelido: "TRABALHO, ADMINISTRAÇÃO E SERVIÇO PÚBLICO",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: BuildIcon,
        title: "ABC",
        color: orange[100],
        route: '',
    },
    {
        id: 2016,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2016",
        sigla:"CVT",
        nome: "Comissão de Viação e Transportes",
        apelido: "VIAÇÃO E TRANSPORTES",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: DirectionsBusIcon,
        title: "ABC",
        color: red[100],
        route: '',
    },
    {
        id: 2017,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2017",
        sigla:"CINDRA",
        nome: "Comissão de Integração Nacional, Desenvolvimento Regional e da Amazônia",
        apelido: "INTEGRAÇÃO NACIONAL, DESENV. REGIONAL E AMAZÔNIA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: DeviceHubIcon,
        title: "ABC",
        color: green[100],
        route: '',
    },
    {
        id: 2018,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/2018",
        sigla:"CREDN",
        nome: "Comissão de Relações Exteriores e de Defesa Nacional",
        apelido: "RELAÇÕES EXTERIORES E DE DEFESA NACIONAL",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: VpnLockIcon, //PublicIcon
        title: "ABC",
        color: red[100],
        route: '',
    },
    {
        id: 5438,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/5438",
        sigla:"CLP",
        nome: "Comissão de Legislação Participativa",
        apelido: "LEGISLAÇÃO PARTICIPATIVA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: GroupAddIcon,
        title: "ABC",
        color: brown[100],
        route: '',
    },
    {
        id: 5503,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/5503",
        sigla:"CSPCCO",
        nome: "Comissão de Segurança Pública e Combate ao Crime Organizado",
        apelido: "SEGURANÇA PÚBLICA E COMBATE AO CRIME ORGANIZADO",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: SecurityIcon, //VerifiedUserIcon,
        title: "ABC",
        color: red[100],
        route: '',
    },
    {
        id: 6066,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/6066",
        sigla:"CTUR",
        nome: "Comissão de Turismo",
        apelido: "TURISMO",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: WorkIcon,
        title: "ABC",
        color: orange[100],
        route: '',
    },
    {
        id: 6174,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/6174",
        sigla:"CMADS",
        nome: "Comissão de Meio Ambiente e Desenvolvimento Sustentável",
        apelido: "MEIO AMBIENTE E DESENVOLVIMENTO SUSTENTÁVEL",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: NaturePeopleIcon,
        title: "ABC",
        color: green[100],
        route: '',
    },
    {
        id: 536996,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/536996",
        sigla:"CCULT",
        nome: "Comissão de Cultura",
        apelido: "CULTURA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: LocalLibraryIcon,
        title: "ABC",
        color: purple[100],
        route: '',
    },
    {
        id: 537236,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/537236",
        sigla:"CESPO",
        nome: "Comissão do Esporte",
        apelido: "ESPORTE",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: PoolIcon,
        title: "ABC",
        color: blue[100],
        route: '',
    },
    {
        id: 537480,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/537480",
        sigla:"CPD",
        nome: "Comissão de Defesa dos Direitos das Pessoas com Deficiência",
        apelido: "DEFESA DOS DIREITOS DAS PESSOAS COM DEFICIÊNCIA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: AccessibleIcon,
        title: "ABC",
        color: orange[100],
        route: '',
    },
    {
        id: 537870,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/537870",
        sigla:"CMULHER",
        nome: "Comissão de Defesa dos Direitos da Mulher",
        apelido: "DEFESA DOS DIREITOS DA MULHER",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: PregnantWomanIcon,
        title: "ABC",
        color: pink[100],
        route: '',
    },
    {
        id: 537871,
        uri: "https://dadosabertos.camara.leg.br/api/v2/orgaos/537871",
        sigla: "CIDOSO",
        nome: "Comissão de Defesa dos Direitos da Pessoa Idosa",
        apelido: "DEFESA DOS DIREITOS DA PESSOA IDOSA",
        codTipoOrgao: 2,
        tipoOrgao: "Comissão Permanente",
        icon: ListIcon,
        title: "ABC",
        color: grey[300],
        route: '',
    }
];

export default comissoes